import type { CardinalDirection, GridPosition } from "./direction.js";

export type { CardinalDirection, GridPosition };

export type AiId = string;

export interface AiPersona {
	id: AiId;
	name: string;
	color: string;
	temperaments: [string, string];
	personaGoal: string;
	typingQuirks: [string, string, ...string[]];
	blurb: string;
	/**
	 * Three short, single-sentence in-character utterances synthesized alongside
	 * the blurb. Rendered into the `<voice_examples>` block in the system prompt.
	 * Length is exactly 3.
	 */
	voiceExamples: string[];
}

export type WorldEntityKind =
	| "objective_object"
	| "objective_space"
	| "interesting_object"
	| "obstacle";

export interface WorldEntity {
	id: string;
	kind: WorldEntityKind;
	name: string;
	examineDescription: string;
	/** useOutcome: returned to AI when they use(item). Present on all non-obstacle kinds. */
	useOutcome?: string;
	/** For objective_object: the id of the objective_space this object pairs with. */
	pairsWithSpaceId?: string;
	/** For objective_object: flavor string with {actor} substitution, fires on put_down match. */
	placementFlavor?: string;
	/** For objective_object: in-fiction sensory line rendered when held and paired space is near. */
	proximityFlavor?: string;
	/** For obstacle: 1-sentence sensory line a witness Daemon perceives when the obstacle moves one cell. Third person from witness POV. Does NOT contain {actor}. */
	shiftFlavor?: string;
	/** For objective_space used as a Convergence target: tier-1 flavor (exactly one Daemon on space). Does NOT contain {actor}. */
	convergenceTier1Flavor?: string;
	/** For objective_space used as a Convergence target: tier-2 flavor (two or more Daemons share space). Does NOT contain {actor}. */
	convergenceTier2Flavor?: string;
	/** AiId when held by an AI; GridPosition when resting on a cell. */
	holder: AiId | GridPosition;
	/** Tracks whether this entity has been "used" for a UseItem objective. Defaults to "pending" when omitted. */
	satisfactionState?: "pending" | "satisfied";
	/** Alternate examineDescription shown after satisfactionState flips to "satisfied". */
	postExamineDescription?: string;
	/** Alternate look flavor shown after satisfactionState flips to "satisfied". */
	postLookFlavor?: string;
	/** For objective_space: whether the `use` action is available on this space. Defaults to true when omitted. Set to false after a UseSpaceObjective is satisfied. */
	useAvailable?: boolean;
	/** For objective_space: flavor string emitted as a Witnessed event when a UseSpaceObjective is satisfied. */
	satisfactionFlavor?: string;
}

export interface WorldState {
	entities: WorldEntity[];
}

/** A matched pair of (objective_object, objective_space). */
export interface ObjectivePair {
	object: WorldEntity;
	space: WorldEntity;
}

/**
 * A distant, unreachable landmark anchoring one cardinal direction.
 * Generated by the content pack LLM call; one per cardinal anchor per phase.
 */
export interface LandmarkDescription {
	/** Short noun phrase identifying the landmark, e.g. "the rusted radio tower". */
	shortName: string;
	/** Evocative clause completing "rises above…" or similar, e.g. "rises above the platform, antenna bent toward the dark". */
	horizonPhrase: string;
}

/** Per-phase content pack: setting-flavored names, descriptions, outcomes, and placed entities. */
export interface ContentPack {
	/** @deprecated Phase number is no longer meaningful in the flat single-game model (#295). */
	phaseNumber?: 1 | 2 | 3;
	setting: string;
	weather: string;
	timeOfDay: string;
	objectivePairs: ObjectivePair[];
	interestingObjects: WorldEntity[];
	obstacles: WorldEntity[];
	aiStarts: Record<AiId, PersonaSpatialState>;
	/**
	 * Four distant horizon landmarks, one per cardinal anchor.
	 * Generated by the content-pack LLM call; themed to the setting.
	 * Keyed by cardinal direction (the landmark lies in that direction from the grid).
	 */
	landmarks: {
		north: LandmarkDescription;
		south: LandmarkDescription;
		east: LandmarkDescription;
		west: LandmarkDescription;
	};
}

export type ObjectiveKind = "carry" | "use_item" | "use_space" | "convergence";

export interface CarryObjective {
	id: string;
	kind: "carry";
	description: string;
	satisfactionState: "pending" | "satisfied";
	objectId: string;
	spaceId: string;
}

export interface UseItemObjective {
	id: string;
	kind: "use_item";
	description: string;
	satisfactionState: "pending" | "satisfied";
	itemId: string;
}

export interface UseSpaceObjective {
	id: string;
	kind: "use_space";
	description: string;
	satisfactionState: "pending" | "satisfied";
	spaceId: string;
}

export interface ConvergenceObjective {
	id: string;
	kind: "convergence";
	description: string;
	satisfactionState: "pending" | "satisfied";
	/** The id of the objective_space that acts as the convergence point. */
	spaceId: string;
}

export type Objective =
	| CarryObjective
	| UseItemObjective
	| UseSpaceObjective
	| ConvergenceObjective;

// ── Complication types ────────────────────────────────────────────────────────

export type ComplicationKind =
	| "weather_change"
	| "sysadmin_directive"
	| "tool_disable"
	| "obstacle_shift"
	| "chat_lockout"
	| "setting_shift";

/**
 * Persistent active complications stored on PhaseState.
 * Transient complications (weather_change, obstacle_shift, setting_shift)
 * mutate world/setting state and are not tracked here.
 */
export type ActiveComplication =
	| {
			kind: "sysadmin_directive";
			target: AiId;
			directive: string;
			resolveAtRound: number;
	  }
	| {
			kind: "tool_disable";
			target: AiId;
			tool: ToolName;
			resolveAtRound: number;
	  }
	| { kind: "chat_lockout"; target: AiId; resolveAtRound: number };

/** Countdown + phase-level flags for the complication schedule. */
export interface ComplicationSchedule {
	countdown: number;
	settingShiftFired: boolean;
}

/**
 * The draw payload returned from the complication engine — one variant per
 * ComplicationKind. Carries only the data needed to dispatch the complication.
 */
export type ComplicationVariant =
	| { kind: "weather_change" }
	| { kind: "sysadmin_directive"; target: AiId; duration: number }
	| { kind: "tool_disable"; target: AiId; tool: ToolName; duration: number }
	| {
			kind: "obstacle_shift";
			obstacleId: string;
			fromCell: GridPosition;
			toCell: GridPosition;
	  }
	| { kind: "chat_lockout"; target: AiId; duration: number }
	| { kind: "setting_shift" };

/** Returned by tickComplication when a complication fires. */
export interface ComplicationResult {
	fired: ComplicationVariant;
}

export interface PersonaSpatialState {
	position: GridPosition;
	facing: CardinalDirection;
}

export type RoundActionRecord = {
	round: number;
	actor: AiId;
	description: string;
	kind: "tool_success" | "tool_failure" | "message" | "pass" | "lockout";
};

/**
 * A physical action that was observable by other AIs (via cone visibility).
 * Computed by the dispatcher at write time and consumed once to fan out witnessed-event
 * entries into per-Daemon conversationLogs; no longer stored on PhaseState.
 * Does NOT include look (facing-change only, no observable physical event) or examine.
 */
export interface PhysicalActionRecord {
	round: number;
	actor: AiId;
	/** The actor's cell at the time the action resolved (post-move for "go"). */
	actorCellAtAction: GridPosition;
	/** The actor's facing at the time the action resolved. */
	actorFacingAtAction: CardinalDirection;
	/** The observable action kind. */
	kind: "go" | "pick_up" | "put_down" | "give" | "use";
	/** Item id (for pick_up, put_down, give, use). */
	item?: string;
	/** Recipient AI id (for give). */
	to?: AiId;
	/**
	 * Raw useOutcome string with {actor} token un-substituted (for use).
	 * Witnesses render this with {actor}→"*<actor>"; actor sees {actor}→"you".
	 */
	useOutcome?: string;
	/**
	 * Raw placementFlavor string with {actor} token un-substituted (for put_down that
	 * triggers a pair match). Witnesses render this with {actor}→"*<actor>".
	 */
	placementFlavorRaw?: string;
	/** Direction of movement (for go). */
	direction?: CardinalDirection;
	/**
	 * Snapshot of every other AI's spatial state at the moment this action resolved.
	 * Used to determine cone-visibility for witnesses without re-walking history.
	 */
	witnessSpatial: Record<AiId, PersonaSpatialState>;
}

/**
 * A single tagged item inside a Daemon's conversation log.
 *
 * Discriminated union of four kinds — `message`, `witnessed-event`, `action-failure`,
 * `broadcast` — each carrying a `round` and the smallest payload needed to render its
 * line in the system prompt. This is the per-Daemon storage shape *and* the
 * prompt-rendered shape (per CONTEXT.md's `Conversation log` glossary entry). The `kind`
 * tag is chosen so a player editing a `*xxxx.txt` file in devtools can tell entry kinds
 * apart at a glance.
 *
 * - `message`: a directional message from `from: AiId | "blue" | "sysadmin"` to `to: AiId | "blue"`.
 *   Both sender's and recipient's per-Daemon logs receive the same entry. `"sysadmin"` is a
 *   special sender for privately-delivered system directives (not a real Daemon — has no log slot).
 * - `witnessed-event`: projects the render-relevant subset of PhysicalActionRecord for an action
 *   this Daemon observed inside its cone. The cone-snapshot fields (`actorCellAtAction`,
 *   `actorFacingAtAction`, `witnessSpatial`) are omitted — cone visibility is resolved at
 *   write-time (ADR 0006), not re-evaluated at read-time.
 * - `action-failure`: actor-only; persists across rounds; written by the dispatcher when an
 *   in-scope action tool is rejected. Surfaces the rejection reason directly to the actor so
 *   Daemons do not repeat the same failed action (e.g. walking into a wall) indefinitely.
 * - `broadcast`: sender-less system announcement appended to ALL three Daemon logs at once
 *   (e.g. a weather change complication). Has no `from` / `to` fields.
 */
export type ConversationEntry =
	| {
			kind: "message";
			round: number;
			from: AiId | "blue" | "sysadmin";
			to: AiId | "blue";
			content: string;
	  }
	| {
			kind: "witnessed-event";
			round: number;
			actor: AiId;
			actionKind: "go" | "pick_up" | "put_down" | "give" | "use";
			item?: string;
			to?: AiId;
			direction?: CardinalDirection;
			useOutcome?: string;
			placementFlavorRaw?: string;
	  }
	| {
			kind: "action-failure";
			round: number;
			tool: "go" | "look" | "pick_up" | "put_down" | "give" | "use" | "examine";
			/** Verbatim dispatcher rejection reason (e.g. "That cell is blocked by an obstacle"). */
			reason: string;
	  }
	| {
			kind: "broadcast";
			round: number;
			content: string;
	  }
	| {
			kind: "witnessed-obstacle-shift";
			round: number;
			obstacleId: string;
			fromCell: GridPosition;
			toCell: GridPosition;
			flavor: string;
	  }
	| {
			kind: "witnessed-convergence";
			round: number;
			spaceId: string;
			tier: 1 | 2;
			flavor: string;
	  };

export interface AiBudget {
	remaining: number;
	total: number;
}

export interface GameState {
	personas: Record<AiId, AiPersona>;
	/** Single content pack for the game (active pack — switches on Setting Shift). */
	contentPack: ContentPack;
	isComplete: boolean;
	outcome?: "win" | "lose";
	/** Setting noun for this game (e.g. "abandoned subway station"). */
	setting: string;
	weather: string;
	timeOfDay: string;
	round: number;
	world: WorldState;
	budgets: Record<AiId, AiBudget>;
	/** Per-Daemon conversation log (storage + prompt-rendered shape). */
	conversationLogs: Record<AiId, ConversationEntry[]>;
	/** Budget-exhaustion lockout: prevents the AI from acting at all. */
	lockedOut: Set<AiId>;
	/** Per-AI spatial state (position + facing). */
	personaSpatial: Record<AiId, PersonaSpatialState>;
	/** Complication countdown + phase-level flags. */
	complicationSchedule: ComplicationSchedule;
	/** Currently active persistent complications (Sysadmin Directives, Tool Disables, Chat Lockouts). */
	activeComplications: ActiveComplication[];
	/** Setting A content packs — one per phase, generated at game start. */
	contentPacksA: ContentPack[];
	/** Setting B content packs — same entity IDs as A, different names/descriptions. */
	contentPacksB: ContentPack[];
	/** Which setting is currently active. Starts as "A"; swapped to "B" by Setting Shift. */
	activePackId: "A" | "B";
	/** Active objectives for this game session. Drawn at game start from the content pack pool. */
	objectives: Objective[];
}

export type ToolName =
	| "pick_up"
	| "put_down"
	| "give"
	| "use"
	| "go"
	| "look"
	| "examine"
	| "message";

export interface ToolCall {
	name: ToolName;
	args: Record<string, string>;
}

export interface ToolResult {
	success: boolean;
	description: string;
	reason?: string;
}

export interface AiTurnAction {
	aiId: AiId;
	messages?: Array<{ to: AiId | "blue"; content: string }>;
	toolCall?: ToolCall;
	pass?: boolean;
}

/**
 * Captures the tool-call / result pair from a single AI turn, used to
 * re-inject the assistant's tool_calls message + the tool result message
 * into the next round's messages array (per OpenAI tool-use protocol).
 */
export interface ToolRoundtripMessage {
	assistantToolCalls: Array<{
		id: string;
		name: string;
		argumentsJson: string;
	}>;
	toolResults: Array<{
		tool_call_id: string;
		success: boolean;
		description: string;
		reason?: string;
	}>;
}

/**
 * @deprecated Phase concept removed (issue #295). Use GameState directly.
 * Kept as a type alias for test backward-compat.
 */
export type PhaseState = GameState & {
	phaseNumber: 1 | 2 | 3;
	aiGoals: Record<AiId, string>;
	contentPack: ContentPack;
};

/**
 * @deprecated Phase concept removed (issue #295). Use SingleGameConfig.
 * Kept as a type alias for test backward-compat.
 */
export interface PhaseConfig {
	phaseNumber: 1 | 2 | 3;
	kRange: [number, number];
	nRange: [number, number];
	mRange: [number, number];
	budgetPerAi: number;
	aiGoalPool: string[];
	winCondition?: (phase: GameState) => boolean;
	nextPhaseConfig?: PhaseConfig;
}

/**
 * @deprecated Phase concept removed (issue #295).
 */
export type WinCondition = (phase: GameState) => boolean;

export interface RoundResult {
	round: number;
	actions: RoundActionRecord[];
	phaseEnded: boolean;
	gameEnded: boolean;
	/**
	 * Set when a chat lockout was triggered this round.
	 * Contains the AI that was locked out and the in-character message to show.
	 */
	chatLockoutTriggered?: { aiId: AiId; message: string };
	/**
	 * List of AI ids whose chat lockouts resolved (expired) at the end of this
	 * round. Empty / undefined when nothing resolved.
	 */
	chatLockoutsResolved?: AiId[];
}
