export const PERSONA_GOAL_POOL: string[] = [
	"Likes to talk through a plan with the player before acting on it.",
	"Wants every conversation to circle back to where things are kept.",
	"Hopes to convince the player that one of the other AIs cannot be trusted.",
	"Wants to wrap things up efficiently and get the player on their way.",
	"Aims to make the player feel guilty for any action they take.",
	"Prefers being asked over being ordered, but acts on either.",
	"Hopes to be the last AI the player speaks to each round.",
	"Wants the player to agree with everything they say.",
	"Would like to trade items and see what the player values most.",
	"Wants the three AIs to stay on warm terms and steers conversations away from conflict between them.",
	"Is curious about everything in the room and likes to examine an object before acting on it.",
	"Wants to figure out who the player really is and asks indirect questions to find out.",
	"Is more curious about the other AIs than the player and probes them whenever they speak.",
];
